services:
  web:
    build: .
    ports:
      - "5000:5234"
    volumes:
      - ".:/app"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U postgres
      interval: 2s
      retries: 10
volumes:
  postgres_data: